// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4W_p7nM8xqtOKzdMhuX5suXjeYWP5V44',
    appId: '1:481163825232:web:bbbf7a7a81327089730155',
    messagingSenderId: '481163825232',
    projectId: 'my-own-social-media-app',
    authDomain: 'my-own-social-media-app.firebaseapp.com',
    storageBucket: 'my-own-social-media-app.firebasestorage.app',
    measurementId: 'G-RT91GWD4QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzgs-MfC-q7faYoDwS1-33JfL60g-ZC_Y',
    appId: '1:481163825232:android:7a3eab0617c8865a730155',
    messagingSenderId: '481163825232',
    projectId: 'my-own-social-media-app',
    storageBucket: 'my-own-social-media-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdvzIjKM90mPREinh9r32FaeJOUhRK7yo',
    appId: '1:481163825232:ios:e7210dfb3fcb7df7730155',
    messagingSenderId: '481163825232',
    projectId: 'my-own-social-media-app',
    storageBucket: 'my-own-social-media-app.firebasestorage.app',
    iosBundleId: 'com.example.myOwnSocialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdvzIjKM90mPREinh9r32FaeJOUhRK7yo',
    appId: '1:481163825232:ios:e7210dfb3fcb7df7730155',
    messagingSenderId: '481163825232',
    projectId: 'my-own-social-media-app',
    storageBucket: 'my-own-social-media-app.firebasestorage.app',
    iosBundleId: 'com.example.myOwnSocialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4W_p7nM8xqtOKzdMhuX5suXjeYWP5V44',
    appId: '1:481163825232:web:52cc3d48850998b3730155',
    messagingSenderId: '481163825232',
    projectId: 'my-own-social-media-app',
    authDomain: 'my-own-social-media-app.firebaseapp.com',
    storageBucket: 'my-own-social-media-app.firebasestorage.app',
    measurementId: 'G-PRBD6ZWL2E',
  );
}
