// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdXJZm8K9YVigJ9IVEo09NYJsZfZDGAMM',
    appId: '1:452864114270:web:ca362590c18bf4fa947ecf',
    messagingSenderId: '452864114270',
    projectId: 'rebelgram-v2',
    authDomain: 'rebelgram-v2.firebaseapp.com',
    storageBucket: 'rebelgram-v2.firebasestorage.app',
    measurementId: 'G-RHKXQ0KWGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvGq4MCg3jvIvCPo8v_nqKHlMqpSFPWss',
    appId: '1:452864114270:android:2d253452b914789c947ecf',
    messagingSenderId: '452864114270',
    projectId: 'rebelgram-v2',
    storageBucket: 'rebelgram-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdvzIjKM90mPREinh9r32FaeJOUhRK7yo',
    appId: '1:481163825232:ios:e7210dfb3fcb7df7730155',
    messagingSenderId: '481163825232',
    projectId: 'my-own-social-media-app',
    storageBucket: 'my-own-social-media-app.firebasestorage.app',
    iosBundleId: 'com.example.myOwnSocialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdvzIjKM90mPREinh9r32FaeJOUhRK7yo',
    appId: '1:481163825232:ios:e7210dfb3fcb7df7730155',
    messagingSenderId: '481163825232',
    projectId: 'my-own-social-media-app',
    storageBucket: 'my-own-social-media-app.firebasestorage.app',
    iosBundleId: 'com.example.myOwnSocialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdXJZm8K9YVigJ9IVEo09NYJsZfZDGAMM',
    appId: '1:452864114270:web:1b211679ca72ba09947ecf',
    messagingSenderId: '452864114270',
    projectId: 'rebelgram-v2',
    authDomain: 'rebelgram-v2.firebaseapp.com',
    storageBucket: 'rebelgram-v2.firebasestorage.app',
    measurementId: 'G-WLMBD0CQE7',
  );

}